server:
  servlet:
    session:
      cookie:
        max-age: 600
  port: 8001
  tomcat:
    max-connections: 200
    max-threads: 200
    ssl:
      key-store: product-store.p12
      key-store-password: password
      keyStoreType: PKCS12
      keyAlias: product-store
    enabled: false
    ciphers: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    protocol: TLS
    enabled-protocols: TLSv1.2

spring:
  application:
    name: product-store-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36}::%M:%L - %msg%n"
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: info
    root: info
    org.springframework.web: info
    org.hibernate: info
    com.unicomer.productstore: debug
  file:
    name: product-store.log
